### PR TITLE
Add [Gen 1] Random Auto Level Adjusted format

### PR DESCRIPTION
**Pull request by Estu**
Create a new format for Generation 1 random battles in which pokemon levels are auto-adjusted based on their past performance in this format. Over time, as we accrue match data, each pokemon should be equally valuable on average.

### CODE REVIEW

**Comment by panpawn** [comment]
This branch now has conflicts that you'll have to resolve before I can merge it.

Also, can you squash your commits? Thanks!

**Comment by Estu** [comment]
I've resolved the conflicts. I spent a couple hours trying to squash my commits but I had to do a ton of unrelated conflict resolutions in the process (I guess because of the amount of time that's passed since I made these commits) and I don't know that it worked. I have no idea how to use git.

**Comment by panpawn** [comment]
By having config/pokemon-match-records.tsv on GitHub, every time I update it will set it back to whatever is on GitHub.

Is this intended?

**Comment by Estu** [comment]
No - that version of the file is meant to be the initial state, and then the server is meant to update the file as matches are recorded. Sounds like I'll need to implement some logic to make that work - or do you guys have some established procedure for data files of this kind? I guess what I'll need to do is get rid of that file from the repository, and then write code to create an initial version of the file if it doesn't exist.

**Comment by panpawn** [comment]
>do you guys have some established procedure for data files of this kind?

> I guess what I'll need to do is get rid of that file from the repository, and then write code to create an initial version of the file if it doesn't exist.

You answered your own question

**Comment by Estu** [comment]
OK - I'll make those changes today.

**Comment by panpawn** [comment]
Here's an example of me doing that with a JSON file - https://github.com/panpawn/Gold-Server/blob/master/gold-plugins/gold-users.js#L24-L34

**Comment by panpawn** [comment]
Oh boy, it looks like the commits got messed up on here.

You can make a new pull request instead of fixing them, I suppose. :ss

**Comment by Estu** [comment]
Yep. Probably has to do with my trying to squash those commits. I'll make a new pull request.

**Pull request closed without merging**
