### PR TITLE
Re-implement Gen 1 Random Auto Level Adjusted format

### PR DESCRIPTION
**Pull request by Estu**
Re-implement the earlier Gen 1 Random Auto Level Adjusted format given the new changes in the main Pokemon Server code. The approach is
basically the same as before, but we now use a global pokemonRecord object to maintain the state of the record across various pieces of code.

### CODE REVIEW

**Comment by panpawn** [comment]
Yep, Travis failing seems unrelated. Did you test this reimplementation btw?

**Comment by Estu** [comment]
Yep - played several battles in the new mode and a couple battles in existing modes. Seems to work fine.

**Comment by panpawn** [comment]
I just restarted the server with these changes, so they're now live n_n

**Comment by Estu** [comment]
Sweet!

**Pull request merged**
